const ActionType = {
    LOADING_OPEN: 'LOADING_OPEN',
    MODAL_TAFSIR_OPEN: 'MODAL_TAFSIR_OPEN',
    MESSAGE_SORRY: 'MESSAGE_SORRY',
    UNSET_MODAL: 'UNSET_MODAL',
    ADD_LIKE: 'ADD_LIKE',
    REMOVE_LIKE: 'REMOVE_LIKE',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
    ADD_BOOK: 'ADD_BOOK',
    REMOVE_BOOK: 'REMOVE_BOOK',
    RESTORE: 'RESTORE',
    SET_THEME: 'SET_THEME',
  }
  export default ActionType